SELECT * FROM EMPLOYEE;

SELECT * FROM DEPARTMENT;

INSERT INTO DEPARTMENT VALUES('JavaScript') 
INSERT INTO DEPARTMENT VALUES('PHP') 

ALTER TABLE EMPLOYEE ADD SALARY DECIMAL(10,2)

--After above query added the salary in employee table manually

SELECT top 5 * from EMPLOYEE order by 1 desc;

SELECT top 5 EmpID,EmpName,Email from EMPLOYEE order By EmpName;

select DISTINCT DeptID,EmpName from employee where SALARY>17000;

SELECT * FROM EMPLOYEE WHERE EmpName LIKE 'A%';

SELECT * FROM EMPLOYEE WHERE DeptID=301 AND SALARY >16000;

SELECT * FROM EMPLOYEE WHERE DeptID=301 OR SALARY >17000;

SELECT * FROM EMPLOYEE WHERE SALARY IS NULL;

SELECT * FROM EMPLOYEE WHERE SALARY IS NOT NULL;

SELECT * FROM EMPLOYEE WHERE DEPTID BETWEEN 201 AND 501;


SELECT COUNT(SALARY) FROM EMPLOYEE;
SELECT COUNT(*) FROM EMPLOYEE;

SELECT MAX(SALARY) AS [Maximum Salary] from EMPLOYEE;

SELECT MIN(SALARY) AS [Minimum Salary] from EMPLOYEE ;

SELECT EmpID,SALARY from EMPLOYEE WHERE SALARY<17000 GROUP BY EMPID,SALARY ORDER BY SALARY DESC;

SELECT EmpID,SALARY,EMPNAME from EMPLOYEE WHERE SALARY>16000 GROUP BY EMPID,SALARY,EmpName HAVING EmpID>6 ORDER BY SALARY DESC;


-----JOINS----

SELECT * FROM EMPLOYEE AS EMP INNER JOIN DEPARTMENT AS DEPT ON EMP.DeptID=DEPT.DeptID;

SELECT E.EMPID,E.EMPNAME,D.DEPTNAME,E.EMAIL  FROM EMPLOYEE AS E INNER JOIN DEPARTMENT AS D ON E.DeptID=D.DeptID;

SELECT E.EMPID,E.EMPNAME,E.CONTACT,D.DEPTID,D.DEPTNAME FROM EMPLOYEE AS E LEFT JOIN DEPARTMENT AS D ON E.DeptID=D.DeptID;

SELECT E.EMPID,E.EMPNAME,E.CONTACT,E.EMAIL,D.DEPTID,D.DEPTNAME FROM EMPLOYEE AS E RIGHT JOIN DEPARTMENT AS D ON E.DeptID=D.DeptID;

SELECT E1.EmpID,E1.EMPNAME,E1.CONTACT FROM EMPLOYEE AS E1 ,EMPLOYEE E2 WHERE E1.SALARY<>E2.SALARY AND E1.DeptID=E2.DeptID ORDER BY E1.EmpID DESC;





